<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.cmiethling.mplex</groupId>
    <artifactId>mplex-suite</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>MPLEX Suite</name>
    <description>
        Aggregator that manages all modules and parent that defines plugin versions and dependencies.
    </description>

    <!-- TODO add maven profile to maven central website -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.4</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- OpenAPI + Generator -->
        <springdoc.version>2.8.9</springdoc.version>
        <openapi-generator.version>7.14.0</openapi-generator.version>
        <jackson-databind-nullable.version>0.2.6</jackson-databind-nullable.version>
        <build-helper-maven-plugin.version>3.6.1</build-helper-maven-plugin.version>
    </properties>

    <distributionManagement>
        <!-- This supposed to be the place where the documentation will be deployed. It is required by some plugins. -->
        <site>
            <id>mplex-suite-site</id>
            <name>MPLEX Suite Site</name>
            <url>http://localhost:8090/mplex</url>
        </site>
    </distributionManagement>

    <!-- All modules are build with this reactor. -->
    <modules>
        <module>rest-api</module>
        <module>device</module>
        <module>emulator</module>
        <module>client</module>
    </modules>

    <dependencyManagement>
        <dependencies>

            <!--
                Mplex project dependencies, used by Mplex applications.
                Do not add the top-level projects (e.g. applications, plugins) itself!
            -->
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>device</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>rest-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>client-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>server-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- OpenAPI -->
            <!-- docs -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <!-- otherwise import org.openapitools.jackson.nullable.JsonNullable; won't be found-->
            <dependency>
                <groupId>org.openapitools</groupId>
                <artifactId>jackson-databind-nullable</artifactId>
                <version>${jackson-databind-nullable.version}</version>
            </dependency>

            <!-- Test dependencies -->
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>emulator</artifactId>
                <version>${project.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- All module will have these dependencies by default -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>

                <!-- OpenAPI Generator -->
                <plugin>
                    <groupId>org.openapitools</groupId>
                    <artifactId>openapi-generator-maven-plugin</artifactId>
                    <version>${openapi-generator.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <!-- OpenAPI: only remove generated sources -->
    <!-- <profiles>
        <profile>
            <id>clean-generated</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>build-helper-maven-plugin</artifactId>
                        <version>${build-helper-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>clean-generated-sources</id>
                                <phase>clean</phase>
                                <configuration>
                                    <directories>
                                        <directory>${project.build.directory}/generated-sources</directory>
                                    </directories>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles> -->
</project>
