<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cmiethling.mplex</groupId>
        <artifactId>mplex-suite</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>rest-api</artifactId>
    <packaging>pom</packaging>
    <name>REST API</name>

    <modules>
        <module>client-api</module>
        <module>server-api</module>
    </modules>

    <dependencies>
        <!-- OpenAPI -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <!-- OpenAPI Generator -->
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- OpenAPI generator - general settings -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <configuration>
                    <!-- submodules client-api, server-api will fill these values -->
                    <!--suppress UnresolvedMavenProperty -->
                    <apiPackage>${openapi-generator.package}.api</apiPackage>
                    <!--suppress UnresolvedMavenProperty -->
                    <modelPackage>${openapi-generator.package}.model</modelPackage>
                    <!--suppress UnresolvedMavenProperty -->
                    <invokerPackage>${openapi-generator.package}.invoker</invokerPackage>
                    <!-- submodules client-api, server-api will search in (this) parent modul -->
                    <inputSpecRootDirectory>${project.parent.basedir}/src/main/resources/specs</inputSpecRootDirectory>
                    <mergedFileName>merged_spec</mergedFileName>

                    <output>${project.build.directory}/generated-sources/openapi</output>
                    <generateApiTests>false</generateApiTests>
                    <generateModelTests>false</generateModelTests>
                    <configOptions>
                        <dateLibrary>java8</dateLibrary>
                    </configOptions>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>