<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.cmiethling.mplex</groupId>
        <artifactId>rest-api</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>client-api</artifactId>
    <name>Client API</name>

    <properties>
        <openapi-generator.package>com.cmiethling.mplex.client_api</openapi-generator.package>
    </properties>

    <build>
        <plugins>
            <!-- OpenAPI for Client api generation -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <configuration>
                    <!-- https://openapi-generator.tech/docs/generators/java -->
                    <generatorName>java</generatorName>

                    <configOptions>
                        <library>resttemplate</library>
                        <useJakartaEe>true</useJakartaEe>
                        <generateClientAsBean>true</generateClientAsBean>
                    </configOptions>
                </configuration>
                <executions>
                    <!-- will generate client-api code -->
                    <execution>
                        <id>client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>