<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.cmiethling.mplex</groupId>
        <artifactId>rest-api</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>server-api</artifactId>
    <name>Server API</name>

    <properties>
        <openapi-generator.package>com.cmiethling.mplex.server_api</openapi-generator.package>
        <openapi-generator.modelPackage>${openapi-generator.package}.model</openapi-generator.modelPackage>
    </properties>

    <build>
        <plugins>
            <!-- OpenAPI for Server stub generation -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <configuration>
                    <!-- https://openapi-generator.tech/docs/generators/spring  -->
                    <generatorName>spring</generatorName>
                    <generateApiDocumentation>true</generateApiDocumentation>
                    <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>

                    <apiPackage>${openapi-generator.package}.api</apiPackage>
                    <output>${project.build.directory}/generated-sources/openapi</output>
                    <configOptions>
                        <useSpringBoot3>true</useSpringBoot3>
                        <interfaceOnly>true</interfaceOnly>
                        <useResponseEntity>true</useResponseEntity>
                        <useTags>true</useTags>
                        <delegatePattern>true</delegatePattern>
                        <useSpringController>true</useSpringController>
                        <useSwaggerUI>true</useSwaggerUI>
                        <dateLibrary>java8</dateLibrary>
                        <additionalModelTypeAnnotations>
                            @lombok.Getter
                            @lombok.RequiredArgsConstructor
                            <!-- not working... @lombok.SneakyThrows-->
                        </additionalModelTypeAnnotations>
                    </configOptions>
                </configuration>


                <executions>
                    <execution>
                        <id>fluidics</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${openapi-generator.schemadir}/fluidics.yaml</inputSpec>
                            <modelPackage>${openapi-generator.modelPackage}.fluidics</modelPackage>
                        </configuration>
                    </execution>
                    <execution>
                        <id>hv</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${openapi-generator.schemadir}/hv.yaml</inputSpec>
                            <modelPackage>${openapi-generator.modelPackage}.hv</modelPackage>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>