openapi: 3.0.1
info:
  title: Base API
  description: Base definitions for common components and paths
  version: 1.0.0

# merged spec always generates 'servers: - url: "http://localhost:8080"' anyways...
#servers:
#  - url: http://localhost:8091

components:
  schemas:
    BaseRequest:
      type: object
      properties:
        subsystem:
          type: string
          enum: [ fluidics, hv ]
        topic:
          type: string
          example: ""
        parameters:
          type: object
          example: { }
        # not necessary anymore as events are handled by the websocket, and http has request and response by default
        # type:
        #   type: string
        #   enum: [ request ]
        # id:
        #   type: string
        #   format: uuid

    BaseResponse:
      type: object
      properties:
        subsystem:
          type: string
          enum: [ fluidics, hv ]
        topic:
          type: string
          example: ""
        error:
          type: string
          enum: [ noError, invalidSubsystem, invalidTopic, invalidParameters, error ]
          example: noError
        result:
          type: object
          example: { }
        # type:
        #   type: string
        #   enum: [ result ]
        # id:
        #   type: string
        #   format: uuid
