# TODO ev 3.1.x nutzen
openapi: 3.0.1
info:
  title: Fluidics Commands API
  description: API to interact with the fluidics subsystem commands
  version: 1.0.0

# merged spec always generates 'servers: - url: "http://localhost:8080"' anyways...
#servers:
#  - url: http://localhost:8091

paths:
  /restapi/fluidics/SetGelPump:
    post:
      tags: [ fluidics ]
      summary: Send SetGelPump request to the fluidics subsystem
      operationId: setGelPumpCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetGelPumpRequest'
      responses:
        #        TODO add 409 Conflict: pump can't turn on if valve is closed, 400 Bad Request (syntax)
        '200':
          description: Result of SetGelPump command
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetGelPumpResponse'

components:
  schemas:
    SetGelPumpRequest:
      allOf:
        - $ref: 'base.yaml#/components/schemas/BaseRequest'
        - type: object
          required: [ subsystem, topic, parameters ]
          properties:
            subsystem:
              enum: [ fluidics ]
              default: fluidics
            topic:
              enum: [ SetGelPump ]
              default: SetGelPump
            parameters:
              type: object
              required: [ isOn ]
              properties:
                isOn:
                  type: boolean
                  description: Indicates whether the gel pump should be turned on

    SetGelPumpResponse:
      allOf:
        - $ref: 'base.yaml#/components/schemas/BaseResponse'
        - type: object
          required: [ subsystem, topic, result ]
          properties:
            subsystem:
              type: string
              enum: [ fluidics ]
              default: fluidics
            topic:
              type: string
              enum: [ SetGelPump ]
              default: SetGelPump
            result:
              type: object
              required: [ isOn ]
              properties:
                isOn:
                  type: boolean
                  description: The status of the pump after the command
                  example: false
