<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cmiethling.mplex</groupId>
        <artifactId>mplex-suite</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>client-api</artifactId>
    <packaging>pom</packaging>

    <name>Client API</name>

    <properties>
        <openapi-generator.schemadir>${project.parent.basedir}/src/main/resources/schema</openapi-generator.schemadir>
    </properties>

    <modules>
        <module>rest-api-client</module>
        <!-- <module>rest-api-server</module> -->
    </modules>

    <dependencies>
        <!-- OpenAPI -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <!-- OpenAPI Generator -->
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>openapi-generator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
        </dependency>
    </dependencies>

    <!-- <build>
        <plugins>
            &lt;!&ndash; OpenAPI Generator &ndash;&gt;
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <configuration>
                    &lt;!&ndash; configuration for all APIs &ndash;&gt;
                    <generatorName>spring</generatorName>
                    <generateApiDocumentation>true</generateApiDocumentation>
                    <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                    <apiPackage>${openapi-generator.package}.api</apiPackage>
                    <output>${project.build.directory}/generated-sources/openapi</output>
                    <configOptions>
                        <delegatePattern>true</delegatePattern>
                        <useSpringBoot3>true</useSpringBoot3>
                        <useSwaggerUI>true</useSwaggerUI>
                        <useSpringController>true</useSpringController>
                        <interfaceOnly>true</interfaceOnly>
                        <useTags>true</useTags>
                        <dateLibrary>java8</dateLibrary>
                        <additionalModelTypeAnnotations>
                            @lombok.Setter
                            @lombok.Getter
                            @lombok.RequiredArgsConstructor
                            &lt;!&ndash; not working... @lombok.SneakyThrows&ndash;&gt;
                        </additionalModelTypeAnnotations>
                    </configOptions>
                </configuration>


                <executions>
                    <execution>
                        <id>fluidics</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${openapi-generator.schemadir}/fluidics.yaml</inputSpec>
                            <modelPackage>${openapi-generator.modelPackage}.fluidics</modelPackage>
                        </configuration>
                    </execution>
                    <execution>
                        <id>hv</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${openapi-generator.schemadir}/hv.yaml</inputSpec>
                            <modelPackage>${openapi-generator.modelPackage}.hv</modelPackage>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build> -->
</project>